blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('nblog1.urls')),
    path('accounts/', include('allauth.urls')), 
    path('', include('discussion.urls')), # new
]

# 開発環境でのメディアファイルの配信設定
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

discussion/urls.py
from django.urls import path
from . import views

app_name = 'discussion'
urlpatterns = [
    
    # /disc/ -> Discussion List
    path('', views.DiscList.as_view(), name='disc_list'),
    
    # /disc/disc_create/ -> Discussion Create
    path('disc_create/', views.DiscCreate.as_view(), name='disc_create'),
    
    # /disc/disc_update/1/ -> Discussion #1 Update
    path('disc_update/<int:pk>/', views.DiscUpdate.as_view(), name='disc_update'),
    
    # /disc/disc_delete/1/ -> Discussion #1 Delete
    path('disc_delete/<int:pk>/', views.DiscDelete.as_view(), name='disc_delete'),
    
    # /disc/usr_list/1/ -> DiscUser List for Discussion #1
    path('usr_list/<int:disc_id>/', views.UsrList.as_view(), name='usr_list'),
    
    # /disc/usr_update/1/ -> DiscUser #1 Update
    path('usr_update/<int:pk>/', views.UsrUpdate.as_view(), name='usr_update'),
    
    # /disc/usr_delete/1/ -> DiscUser #1 Delete
    path('usr_delete/<int:pk>/', views.UsrDelete.as_view(), name='usr_delete'),

    # /disc/invt_create/1/ -> Invitation Create for Discussion #1
    path('invt_create/<int:disc_id>/', views.InvtCreate.as_view(), name='invt_create'),

    # /disc/invt_delete/1/{usr_list|disc_list}/ -> Invitation #1 Delete
    path('invt_delete/<int:pk>/<str:from>/', views.InvtDelete.as_view(), name='invt_delete'),

    # /disc/disc_join/1/ -> Join to Discussion via Invitation #1
    path('disc_join/<int:invt_id>/', views.DiscJoin.as_view(), name='disc_join'),
]

nblog1/urls.py
from django.urls import path
from . import views, feeds

app_name = 'nblog1'

urlpatterns = [
    path('', views.PublicPostIndexView.as_view(), name='top'),
    path('private/', views.PrivatePostIndexView.as_view(), name='private_post_list'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', views.PostCreate.as_view(), name='post_create'), #add
    path('posts/delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete'), #add
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('reply/create/<int:pk>/', views.ReplyCreate.as_view(), name='reply_create'),

    path('subscribe/email/', views.subscribe_email, name='subscribe_email'),
    path('subscribe/email/register/<str:token>/', views.subscribe_email_register, name='subscribe_email_register'),
    path('subscribe/email/done/', views.subscribe_email_done, name='subscribe_email_done'),
    path('subscribe/email/release/done/', views.subscribe_email_release_done, name='subscribe_email_release_done'),
    path('subscribe/email/release/<str:token>/', views.subscribe_email_release, name='subscribe_email_release'),

    path('posts/suggest/', views.posts_suggest, name='posts_suggest'),
    path('image/upload/', views.image_upload, name='image_upload'),

    path('rss/', feeds.RssLatestPostsFeed(), name='rss'),
    path('atom/', feeds.AtomLatestPostsFeed(), name='atom'),
]

nblog1/models.py
from django.conf import settings
from django.core.mail import EmailMessage
from django.core.signing import dumps
from django.db import models
from django.shortcuts import resolve_url
from django.template.loader import render_to_string
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255, unique=True)

    def __str__(self):
        # 検索フォーム等では、紐づいた記事数を表示する。その場合はpost_countという属性に記事数を持つ。
        if hasattr(self, 'post_count'):
            return f'{self.name}({self.post_count})'
        else:
            return self.name


class Post(models.Model):
    """記事"""
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    attachment = models.FileField('ファイルの追加', blank=True)
    tags = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)

    relation_posts = models.ManyToManyField('self', verbose_name='関連記事', blank=True)
    is_public = models.BooleanField('公開可能か?', default=True)
    description = models.TextField('記事の説明', max_length=130)
    keywords = models.CharField('記事のキーワード', max_length=255, default='記事のキーワード')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', default=timezone.now)

    def __str__(self):
        return self.title

    def line_push(self, request):
        """記事をラインで通知"""
        if settings.USE_LINE_BOT:
            import linebot
            from linebot.models import TextSendMessage
            context = {
                'post': self,
            }
            message = render_to_string('nblog1/mail/send_latest_notify_line_message.txt', context, request)
            line_bot_api = linebot.LineBotApi(settings.LINE_BOT_API_KEY)
            for push in LinePush.objects.all():
                line_bot_api.push_message(push.user_id, messages=TextSendMessage(text=message))

    def email_push(self, request):
        """記事をメールで通知"""
        from_email = settings.DEFAULT_FROM_EMAIL
        for mail_push in EmailPush.objects.filter(is_active=True):
            context = {
                'post': self,
                'token': dumps(mail_push.pk),
            }
            subject = render_to_string('nblog1/mail/send_latest_notify_email_subject.txt', context, request)
            message = render_to_string('nblog1/mail/send_latest_notify_email_message.txt', context, request)
            to = [mail_push.mail]
            email = EmailMessage(subject, message, from_email, to)
            email.send()

    def browser_push(self):
        """記事をブラウザ通知"""
        if settings.USE_WEB_PUSH:
            import requests
            data = {
                'app_id': settings.ONE_SIGNAL_APP_ID,
                'included_segments': ['All'],
                'contents': {'en': self.title},
                'headings': {'en': 'ブログ'},
                'url': resolve_url('nblog1:post_detail', pk=self.pk),
            }
            requests.post(
                "https://onesignal.com/api/v1/notifications",
                headers={'Authorization': settings.ONE_SIGNAL_REST_KEY},
                json=data,
            )


class Comment(models.Model):
    """記事に紐づくコメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    email = models.EmailField('メールアドレス', blank=True, help_text='入力しておくと、返信があった際に通知します。コメント欄には表示されません。')
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]


class Reply(models.Model):
    """コメントに紐づく返信"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]


class LinePush(models.Model):
    """Lineでのプッシュ先を表す"""
    user_id = models.CharField('ユーザーID', max_length=100, unique=True)

    def __str__(self):
        return self.user_id


class EmailPush(models.Model):
    """メールでのプッシュ先を表す"""
    mail = models.EmailField('メールアドレス', unique=True)
    is_active = models.BooleanField('有効フラグ', default=False)

    def __str__(self):
        return self.mail

nblog1/views.py
import json
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.db.models import Q
from django.http import Http404, JsonResponse, HttpResponseBadRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from .forms import (
    PostSearchForm, CommentCreateForm, ReplyCreateForm,
    EmailForm, FileUploadForm, AdminPostCreateForm
)
from .models import Post, Comment, Reply, EmailPush, LinePush, Tag
from django.urls import reverse_lazy

class PostCreate(generic.CreateView): #add
    """記事の作成"""
    form_class = AdminPostCreateForm
    template_name = 'nblog1/post_create.html'
    success_url = reverse_lazy('nblog1:top')
'''
    def form_valid(self, form):
        form.save()
        #super(PostCreate, self).form_valid(form)
        print(dir(self.request))
        print(self.request.POST)
        print(self.request.FILES)

        if self.request.FILES:
            print(self.request.FILES)
        return redirect(self.success_url)
        # return image_upload(self.request)
'''
class PostDelete(generic.DeleteView): #add
    """記事の削除"""
    model = Post
    # template_name = 'nblog1/post_confirm_delete.html'
    success_url = reverse_lazy('nblog1:top')

class PublicPostIndexView(generic.ListView):
    """公開記事の一覧を表示する。"""
    paginate_by = 10
    model = Post
    queryset = Post.objects.filter(is_public=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = PostSearchForm(self.request.GET or None)
        if form.is_valid():
            # 選択したタグが含まれた記事
            tags = form.cleaned_data.get('tags')
            if tags:
                for tag in tags:
                    queryset = queryset.filter(tags=tag)

            # タイトルか本文にキーワードが含まれたもの
            # キーワードが半角スペースで区切られていれば、その回数だけfilterする。つまりAND。
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                for word in key_word.split():
                    queryset = queryset.filter(Q(title__icontains=word) | Q(text__icontains=word))

        queryset = queryset.order_by('-updated_at').prefetch_related('tags')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form
        return context


class PrivatePostIndexView(LoginRequiredMixin, PublicPostIndexView):
    """非公開の記事一覧を表示する。"""
    raise_exception = True
    queryset = Post.objects.filter(is_public=False)


class PostDetailView(generic.DetailView):
    """記事詳細ページを表示する。"""
    model = Post

    def get_queryset(self):
        return super().get_queryset().prefetch_related('tags', 'comment_set__reply_set')

    def get_object(self, queryset=None):
        """その記事が公開か、ユーザがログインしていれば表示する。"""
        post = super().get_object()
        if post.is_public or self.request.user.is_authenticated:
            return post
        else:
            raise Http404


class CommentCreate(generic.CreateView):
    """記事へのコメント作成ビュー。"""
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Post, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.request = self.request
        comment.save()
        return redirect('nblog1:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context


class ReplyCreate(generic.CreateView):
    """コメントへの返信作成ビュー。"""
    model = Reply
    form_class = ReplyCreateForm
    template_name = 'nblog1/comment_form.html'

    def form_valid(self, form):
        comment_pk = self.kwargs['pk']
        comment = get_object_or_404(Comment, pk=comment_pk)
        reply = form.save(commit=False)
        reply.target = comment
        reply.request = self.request
        reply.save()
        return redirect('nblog1:post_detail', pk=comment.target.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        comment = get_object_or_404(Comment, pk=comment_pk)
        context['post'] = comment.target
        return context


@require_POST
def subscribe_email(request):
    """ブログの購読ページ"""
    form = EmailForm(request.POST)
    # メール購読の処理
    if form.is_valid():
        push = form.save()
        context = {
            'token': dumps(push.pk),
        }
        subject = render_to_string('nblog1/mail/confirm_push_subject.txt', context, request)
        message = render_to_string('nblog1/mail/confirm_push_message.txt', context, request)

        from_email = settings.DEFAULT_FROM_EMAIL
        to = [push.mail]
        bcc = [settings.DEFAULT_FROM_EMAIL]
        email = EmailMessage(subject, message, from_email, to, bcc)
        email.send()
        return JsonResponse({'message': 'Thanks!! メールに、登録用のURLを送付しました。'})

    return JsonResponse(form.errors.get_json_data(), status=400)


def subscribe_email_register(request, token):
    """メール購読の確認処理"""
    try:
        user_pk = loads(token, max_age=60 * 60 * 24)  # 1日以内

    # 期限切れ
    except SignatureExpired:
        return HttpResponseBadRequest()

    # tokenが間違っている
    except BadSignature:
        return HttpResponseBadRequest()

    # tokenは問題なし
    else:
        try:
            push = EmailPush.objects.get(pk=user_pk)
        except EmailPush.DoesNotExist:
            return HttpResponseBadRequest()
        else:
            if not push.is_active:
                # まだ仮登録で、他に問題なければ本登録とする
                push.is_active = True
                push.save()
                return redirect('nblog1:subscribe_email_done')

    return HttpResponseBadRequest()


def subscribe_email_release(request, token):
    """メール購読の解除処理"""
    try:
        user_pk = loads(token)

    # tokenが間違っている
    except BadSignature:
        return HttpResponseBadRequest()

    # tokenは問題なし
    else:
        try:
            push = EmailPush.objects.get(pk=user_pk)
        except EmailPush.DoesNotExist:
            return HttpResponseBadRequest()
        else:
            push.delete()
            return redirect('nblog1:subscribe_email_release_done')

    return HttpResponseBadRequest()


def subscribe_email_done(request):
    """メール購読完了"""
    return render(request, 'nblog1/subscribe_email_done.html')


def subscribe_email_release_done(request):
    """メール購読解除の完了"""
    return render(request, 'nblog1/subscribe_email_release_done.html')


@csrf_exempt
def line_callback(request):
    """ラインの友達追加時に呼び出され、ラインのIDを登録する。"""
    if request.method == 'POST':
        request_json = json.loads(request.body.decode('utf-8'))
        events = request_json['events']
        line_user_id = events[0]['source']['userId']

        # チャネル設定のWeb hook接続確認時にはここ。このIDで見に来る。
        if line_user_id == 'Udeadbeefdeadbeefdeadbeefdeadbeef':
            pass

        # 友達追加時・ブロック解除時
        elif events[0]['type'] == 'follow':
            LinePush.objects.create(user_id=line_user_id)

        # アカウントがブロックされたとき
        elif events[0]['type'] == 'unfollow':
            LinePush.objects.filter(user_id=line_user_id).delete()

    return HttpResponse()

"""
def image_upload(request):
    form = FileUploadForm(files=request.FILES)
    if form.is_valid():
        path = form.save()
        url = '{0}://{1}{2}'.format(
            request.scheme,
            request.get_host(),
            path,
        )
        return JsonResponse({'url': url})
    return HttpResponseBadRequest()
"""

def image_upload(request):
    """ファイルのアップロード用ビュー"""
    if request.FILES:
        print(request.FILES)
    return HttpResponse()

def posts_suggest(request):
    """サジェスト候補の記事をJSONで返す。"""
    keyword = request.GET.get('keyword')
    if keyword:
        post_list = [{'pk': post.pk, 'name': str(post)} for post in Post.objects.filter(title__icontains=keyword)]
    else:
        post_list = []
    return JsonResponse({'object_list': post_list})

nblog1/templates/nblog1/base.html
{% load static %}
{% load nblog1 %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <title>{% block meta_title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'nblog1/css/style.css' %}">
    <link rel="stylesheet" href="https://use.typekit.net/wfe6byb.css">
    <script>
      (function(d) {
        var config = {
          kitId: 'jjv2htu',
          scriptTimeout: 3000,
          async: true
        },
        h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
      })(document);
    </script>
    {% block extrahead %}{% endblock %}
</head>
<body>

<main>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<footer id="site-footer">
    <div class="container" id="footer-container">
        {% render_subscribe_section %}

        <hr>
        <ul class="inline-ul">
            {% block link %}{% endblock %}
        </ul>
        <p id="copyright">{% block copyright %}{% endblock %}</p>


    </div>
</footer>

<script>
    document.addEventListener('DOMContentLoaded', e => {

        const searchForm = document.getElementById('search-form');

        for (const tag of document.getElementsByClassName('tag')) {
            tag.addEventListener('click', () => {
                const pk = tag.dataset.pk;
                const checkbox = document.querySelector(`input[name="tags"][value="${pk}"]`);
                if (checkbox.checked) {
                    checkbox.checked = false;
                } else {
                    checkbox.checked = true;
                }
                searchForm.submit();
            });
        }

        for (const check of document.getElementsByName('tags')) {
            check.addEventListener('change', () => {
                searchForm.submit();
            });
        }

        const getCookie = name => {
            if (document.cookie && document.cookie !== '') {
                for (const cookie of document.cookie.split(';')) {
                    const [key, value] = cookie.trim().split('=');
                    if (key === name) {
                        return decodeURIComponent(value);
                    }
                }
            }
        };

        const csrftoken = getCookie('csrftoken');
        const subscribeForm = document.getElementById('subscribe-form');
        const emailErrorArea = document.getElementById('email-errors');

        // 購読ボタンで呼ばれる
        subscribeForm.addEventListener('submit', e => {
            // デフォルトのイベントをキャンセルし、ページ遷移しないように!
            e.preventDefault();

            emailErrorArea.innerHTML = '';

            const url = subscribeForm.action;
            const mail = encodeURIComponent(document.getElementById('id_mail').value);
            fetch(url, {
                method: 'POST',
                body: `mail=${mail}`,
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                    'X-CSRFToken': csrftoken,
                },
            }).then(response => {
                if (response.ok) {
                    response.json().then(response => {
                        const p = document.createElement('p');
                        p.classList.add('helptext');
                        p.textContent = response.message;
                        emailErrorArea.append(p);
                        document.getElementById('id_mail').disabled = true;
                        document.getElementById('subscribe-button').disabled = true;
                    });

                } else {
                    response.json().then(response => {
                        for (const emailError of response.mail) {
                            const p = document.createElement('p');
                            p.classList.add('helptext');
                            p.textContent = emailError.message;
                            emailErrorArea.append(p);
                        }
                    });
                }
            }).catch(error => {
                console.log(error);
            });
        });

    })
    ;
</script>
</body>
</html>

nblog1/templates/nblog1/base_detail.html
{% load static %}
{% load nblog1 %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'nblog1/css/style.css' %}">

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
<main>
    <div class="container">
        <header>
            {% block header %}
            <nav class="navbar navbar-dark bg-dark">
                <a class="navbar-brand">共有Web</a>
                    <a href="{% url 'discussion:disc_list' %}" class="badge badge-light">グループを退出</a>
            </nav>
            {% endblock %}
        </header>
        {% block content %}{% endblock %}
    </div>
</main>

<footer id="site-footer" style="background-color:#343a40">
        <ul class="inline-ul">
            {% block link %}{% endblock %}
        </ul>
        <p id="copyright">{% block copyright %}{% endblock %}</p>
    </div>
</footer>
</body>
</html>

nblog1/templates/nblog1/base_site.html
{% extends 'nblog1/base.html' %}

{% block meta_title %}Title{% endblock %}
{% block meta_description %}サイトの説明{% endblock %}
{% block meta_keywords %}キーワードA, キーワードB{% endblock %}

{% block copyright %}© 2021 Hello World{% endblock %}
{% block link %}
    <li><a href="#">リンクA</a></li>
    <li><a href="#">リンクB</a></li>
    <li><a href="#">リンクC</a></li>
{% endblock %}

nblog1/templates/nblog1/base_site_detail.html
{% extends 'nblog1/base_detail.html' %}

{% block copyright %}© 2021 Hello World{% endblock %}
{% block link %}
    <li><a href="#">リンクA</a></li>
    <li><a href="#">リンクB</a></li>
    <li><a href="#">リンクC</a></li>
{% endblock %}

nblog1/templates/nblog1/post_detail.html
{% extends 'nblog1/base_site_detail.html' %}
{% load nblog1 %}
{% load static %}
{% load humanize %}

{% block content %}
    <div align="right"><a href="{% url 'nblog1:top' %}">TOPへ戻る</a></div>
    <article class="post" id="post-detail">
        <h1 class="post-title">
                {{ post.title }}
        </h1>

        <div class="markdown-body">
            {{ post.text | markdown_to_html }}
        </div>

        <a href="{{ MEDIA_URL }}{{ post.attachment }}">{{ post.attachment }}</a>

        <div>
            <time class="updated_at" datetime="{{ post.updated_at | date:'Y-m-d' }}">
                {{ post.updated_at | naturaltime }}に更新
            </time>

            {% for tag in post.tags.all %}
                <span class="tag-no-click">{{ tag.name }}</span>
            {% endfor %}
        </div>

    </article>

    <section id="relation-posts">
        <h2 class="section-title">関連記事</h2>
        {% for post in post.relation_posts.all %}
            <article class="post">
                <h3 class="post-title"><a href="{% url 'nblog1:post_detail' post.pk %}">{{ post.title }}</a></h3>
                <p class="description">{{ post.description }}</p>
            </article>
        {% empty %}
            <p>関連記事はありません。</p>
        {% endfor %}
    </section>

    <section id="comment">
            <h2 class="section-title">コメント</h2>
            
        <!-- コメント一覧 -->
        {% for comment in post.comment_set.all %}
            <div class="comment">
                <h3>{{ comment.name }}</h3>
                <time class="updated_at"
                      datetime="{{ comment.created_at | date:'Y-m-d' }}">{{ comment.created_at | naturaltime }}</time>
                <div class="description markdown-body">
                    {{ comment.text | markdown_to_html_with_escape}}
                </div>
                <p>
                    <a href="{% url 'nblog1:reply_create' comment.pk %}" target="_blank"
                       rel="nofollow">返信する</a>
                </p>
            </div>


            <!-- リプライ一覧 -->
            {% for reply in comment.reply_set.all %}
                <div class="reply">
                    <h3>{{ reply.name }}</h3>
                    <time class="updated_at"
                          datetime="{{ reply.created_at | date:'Y-m-d' }}">{{ reply.created_at | naturaltime }}</time>
                    <div class="description markdown-body">
                        {{ reply.text | markdown_to_html_with_escape }}
                    </div>
                </div>
            {% endfor %}
            <!-- リプライ一覧終わり -->

        {% empty %}
            <p>まだコメントはありません。</p>
        {% endfor %}
        
        <a href="{% url 'nblog1:comment_create' post.pk %}" target="_blank" rel="nofollow">コメント追加</a>
        
        <!-- コメント一覧終わり -->
    </section>

        <!-- 削除 -->
    <section>
        <div style="margin-top: 100px; margin-bottom: 10px; border-bottom: solid 1px #ccc; padding-bottom: 5px;">
            <h2 style="font-size: 24px; font-weight: bold;">削除</h2>
        </div>
        <a href="{% url 'nblog1:post_delete'  post.pk %}">削除する</a>
    </section>
    <div align="right"><a href="#" class="addlink">ページトップへ</a></div>

{% endblock %}

nblog1/templates/nblog1/post_list.html
{% extends 'nblog1/base_site.html' %}
{% load nblog1 %}
{% load humanize %}

{% block content %}
    <div align="right" style="margin-top:10px;"><a href="{% url 'nblog1:post_create' %}" class="addlink">新規作成</a></div>
    
    <section>
        {% if search_form.cleaned_data.tags %}
            <p class="tags" id="select-tags">選択しているタグ: {% for tag in search_form.cleaned_data.tags %}
                <span class="tag" data-pk="{{ tag.pk }}">{{ tag.name }}</span>{% endfor %}</p>
        {% endif %}
        {% for post in post_list %}
        <div class="card" style="margin-bottom:10px;">
            <h5 class="card-header">
                <form class="navbar navbar-light bg-light">
                    <a>{{ post.title }}</a>
                    <a href="{% url 'nblog1:post_detail' post.pk %}" class="btn btn-primary">詳細へ</a>
                </form>
            </h5>
            
            <div class="card-body">
                    <p class="card-text">{{ post.description }}</p>
                    <time class="updated_at"
                        datetime="{{ post.updated_at | date:'Y-m-d' }}">{{ post.updated_at | naturaltime }}に更新
                    </time>

                    {% for tag in post.tags.all %}
                        <span class="tag" data-pk="{{ tag.pk }}">{{ tag.name }}</span>
                    {% endfor %}
            </div>
        </div>
        
        {% empty %}
            <p class="post">まだ記事がありません。</p>
        {% endfor %}
    </section>

    <nav id="page">
        <!-- 1つ前 の部分 -->
        {% if page_obj.has_previous %}
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}"
               title="前ページへ">前へ</a>
        {% endif %}

        <!-- 1/3 の部分 -->
        <span>{{ page_obj.paginator.num_pages }}ページ中{{ page_obj.number }}ページ目（全{{ page_obj.paginator.count }}件）</span>

        <!-- 1つ後 の部分 -->
        {% if page_obj.has_next %}
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次へ</a>
        {% endif %}
    </nav>
    <div align="right"><a href="#" class="addlink">ページトップへ</a></div>

{% endblock %}

nblog1/templates/nblog1/subscribe_email_done.html
{% extends 'nblog1/base_site_detail.html' %}
{% load humanize %}
{% block meta_title %}購読完了 - {{ block.super }}{% endblock %}

{% block content %}
    <p>ブログのメール購読を完了しました。<br>更新を楽しみにしていてください。</p>
    <p><a href="{% url 'nblog1:top' %}">TOPへ戻る</a></p>
{% endblock %}