blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('nblog1.urls')),
    path('accounts/', include('allauth.urls')), 
    path('', include('discussion.urls')), # new
]

# 開発環境でのメディアファイルの配信設定
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

discussion/urls.py
from django.urls import path
from . import views

app_name = 'discussion'
urlpatterns = [
    
    # /disc/ -> Discussion List
    path('', views.DiscList.as_view(), name='disc_list'),
    
    # /disc/disc_create/ -> Discussion Create
    path('disc_create/', views.DiscCreate.as_view(), name='disc_create'),
    
    # /disc/disc_update/1/ -> Discussion #1 Update
    path('disc_update/<int:pk>/', views.DiscUpdate.as_view(), name='disc_update'),
    
    # /disc/disc_delete/1/ -> Discussion #1 Delete
    path('disc_delete/<int:pk>/', views.DiscDelete.as_view(), name='disc_delete'),
    
    # /disc/usr_list/1/ -> DiscUser List for Discussion #1
    path('usr_list/<int:disc_id>/', views.UsrList.as_view(), name='usr_list'),
    
    # /disc/usr_update/1/ -> DiscUser #1 Update
    path('usr_update/<int:pk>/', views.UsrUpdate.as_view(), name='usr_update'),
    
    # /disc/usr_delete/1/ -> DiscUser #1 Delete
    path('usr_delete/<int:pk>/', views.UsrDelete.as_view(), name='usr_delete'),

    # /disc/invt_create/1/ -> Invitation Create for Discussion #1
    path('invt_create/<int:disc_id>/', views.InvtCreate.as_view(), name='invt_create'),

    # /disc/invt_delete/1/{usr_list|disc_list}/ -> Invitation #1 Delete
    path('invt_delete/<int:pk>/<str:from>/', views.InvtDelete.as_view(), name='invt_delete'),

    # /disc/disc_join/1/ -> Join to Discussion via Invitation #1
    path('disc_join/<int:invt_id>/', views.DiscJoin.as_view(), name='disc_join'),
]

nblog1/urls.py
from django.urls import path
from . import views, feeds

app_name = 'nblog1'

urlpatterns = [
    path('', views.PublicPostIndexView.as_view(), name='top'),
    path('private/', views.PrivatePostIndexView.as_view(), name='private_post_list'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', views.PostCreate.as_view(), name='post_create'), #add
    path('posts/delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete'), #add
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('reply/create/<int:pk>/', views.ReplyCreate.as_view(), name='reply_create'),

    path('subscribe/email/', views.subscribe_email, name='subscribe_email'),
    path('subscribe/email/register/<str:token>/', views.subscribe_email_register, name='subscribe_email_register'),
    path('subscribe/email/done/', views.subscribe_email_done, name='subscribe_email_done'),
    path('subscribe/email/release/done/', views.subscribe_email_release_done, name='subscribe_email_release_done'),
    path('subscribe/email/release/<str:token>/', views.subscribe_email_release, name='subscribe_email_release'),

    path('posts/suggest/', views.posts_suggest, name='posts_suggest'),
    path('image/upload/', views.image_upload, name='image_upload'),

    path('rss/', feeds.RssLatestPostsFeed(), name='rss'),
    path('atom/', feeds.AtomLatestPostsFeed(), name='atom'),
]

discussion/models.py
from datetime import datetime, timezone
from django.conf import settings
from django.db import models


class Discussion(models.Model):
    '''グループ
    '''
    name = models.CharField('グループ名', max_length=50)
    
    class Meta:
        verbose_name = verbose_name_plural = 'グループ'
    
    def __str__(self):
        return self.name


class DiscUser(models.Model):
    '''グループごとのユーザと権限
    '''
    discussion = models.ForeignKey(Discussion, verbose_name='グループ',
        on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name='ユーザ', on_delete=models.CASCADE)
    is_owner = models.BooleanField('所有権', default=False)
    is_editor = models.BooleanField('編集権', default=False)
    
    class Meta:
        verbose_name = verbose_name_plural = 'グループユーザ'
    
    def __str__(self):
        first_name = self.user.first_name
        last_name = self.user.last_name
        
        # 姓と名からフルネームを生成
        if (len(first_name) < 1) and (len(last_name) < 1):
            full_name = ''
        elif len(first_name) < 1:
            full_name = last_name
        elif len(last_name) < 1:
            full_name = first_name
        else:
            full_name = f'{last_name}, {first_name}'
        
        # フルネーム (なければユーザ名) を返す
        if len(full_name) > 0:
            return full_name
        else:
            return self.user.username


class Invitation(models.Model):
    '''グループへの招待
    '''
    discussion = models.ForeignKey(Discussion, verbose_name='グループ',
        on_delete=models.CASCADE)
    inviter = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name='招待する人',
        related_name='inviter', on_delete=models.CASCADE)
    invitee = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name='招待される人',
        related_name='invitee', on_delete=models.CASCADE)
    exp_dt = models.DateTimeField(verbose_name='期限')
    
    class Meta:
        verbose_name = verbose_name_plural = 'グループへの招待'
        ordering = ['exp_dt']
    
    def __str__(self):
        return f'{self.invitee} さんへの {self.discussion} への招待'
    
    def expired(self):
        '''この招待が期限切れかどうかを返す
        '''
        now = datetime.now(timezone.utc)
        return now > self.exp_dt

discussion/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import DiscUser, Invitation
import accounts


class DiscUserAdminForm(forms.ModelForm):
    '''管理サイトでグループユーザを編集する時のフォーム
    '''
    class Meta:
        model = DiscUser
        fields = ('discussion', 'user', 'is_owner', 'is_editor')

    def clean_user(self):
        '''ユーザのバリデーション
        
        user を検証しているという事は、追加フォームである
        '''
        # 追加しようとしている user
        user = self.cleaned_data['user']
        
        # disc_id が入力されていなければ、そっちで検証されるのでスルー
        if 'discussion' not in self.cleaned_data:
            return user
        
        # 同じ discussion, user のレコードがあるか検索
        discussion = self.cleaned_data['discussion']
        dupe = DiscUser.objects.filter(discussion=discussion, user=user)
        
        # 追加なので、同じ discussion, user のレコードが見つかったら重複
        if len(dupe) > 0:
            raise forms.ValidationError('{} はすでに {} のユーザです。'
                .format(user, discussion))
        return user


# Discussion 新規作成時の処理をオーバーライドするサンプルコード
#
# from .models import Discussion
#
# class DiscCreateForm(forms.ModelForm):
#     '''Discussion の追加フォームをカスタマイズ
#     '''
#     class Meta:
#         model = Discussion
#         fields = ('name',)
#     
#     def save(self, commit=True):
#         '''保存時の処理をオーバーライド
#         '''
#         # 保存するべきものを取得する
#         m = super().save(commit=False)
#         
#         # 何らかの処理 (本来はデータを加工したりするところ)
#         print('DiscCreateForm.save()', self.user)
#         
#         if commit:
#             m.save()
#         return m

discussion/views.py
from datetime import datetime, timedelta, timezone
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth import get_user_model
from .view_func import *
from .models import Discussion, DiscUser, Invitation


class DiscList(LoginRequiredMixin, ListView):
    '''Discussion のリストビュー
    
    ログインユーザのグループのみ表示するため、モデルは DiscUser
    '''
    model = DiscUser
    template_name = 'discussion/discussion_list.html'
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # 座組への招待を表示するため、ビューの属性にする
        now = datetime.now(timezone.utc)
        self.invitations = Invitation.objects.filter(invitee=self.request.user,
            exp_dt__gt=now)
        
        return super().get(request, *args, **kwargs)
    
    def get_queryset(self):
        '''リストに表示するレコードをフィルタする
        '''
        # 自分である DiscUser を取得する
        disc_users = DiscUser.objects.filter(user=self.request.user)
        return disc_users


class DiscCreate(LoginRequiredMixin, CreateView):
    '''Discussion の追加ビュー
    '''
    model = Discussion
    fields = ('name',)
    success_url = reverse_lazy('discussion:disc_list')
    
    def form_valid(self, form):
        '''バリデーションを通った時
        '''
        # 保存したレコードを取得する
        new_disc = form.save(commit=True)
        
        # 自分を owner としてグループユーザに追加する
        disc_user = DiscUser(discussion=new_disc, user=self.request.user,
            is_owner=True)
        disc_user.save()
        
        messages.success(self.request, str(new_disc) + " を作成しました。")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        '''追加に失敗した時
        '''
        messages.warning(self.request, "作成できませんでした。")
        return super().form_invalid(form)


class DiscUpdate(LoginRequiredMixin, UpdateView):
    '''Discussion の更新ビュー
    '''
    model = Discussion
    fields = ('name',)
    success_url = reverse_lazy('discussion:disc_list')
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # 所有権を検査する
        test_owner_permission(self, kwargs['pk'])
        
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        '''保存時のリクエストを受けるハンドラ
        '''
        # 所有権を検査する
        test_owner_permission(self, kwargs['pk'])
        
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        '''バリデーションを通った時
        '''
        messages.success(self.request, str(form.instance) + " を更新しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        '''更新に失敗した時
        '''
        messages.warning(self.request, "更新できませんでした。")
        return super().form_invalid(form)


class DiscDelete(LoginRequiredMixin, DeleteView):
    '''Discussion の削除ビュー
    '''
    model = Discussion
    template_name_suffix = '_delete'
    success_url = reverse_lazy('discussion:disc_list')
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # 所有権を検査する
        test_owner_permission(self, kwargs['pk'])
        
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        '''保存時のリクエストを受けるハンドラ
        '''
        # 所有権を検査する
        test_owner_permission(self, kwargs['pk'])
        
        return super().post(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        '''削除した時のメッセージ
        '''
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, str(self.object) + " を削除しました。")
        return result


class UsrList(LoginRequiredMixin, ListView):
    '''DiscUser のリストビュー
    '''
    model = DiscUser
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # アクセス情報からグループユーザを取得しアクセス権を検査する
        disc_user = accessing_disc_user(self, kwargs['disc_id'])
        if not disc_user:
            raise PermissionDenied
        
        # テンプレートから参照できるよう、ビューの属性にしておく
        self.disc_user = disc_user
        
        # 招待中のユーザを表示するため、ビューの属性にする
        self.invitations = Invitation.objects.filter(discussion=disc_user.discussion)
        
        return super().get(request, *args, **kwargs)
    
    def get_queryset(self):
        '''リストに表示するレコードをフィルタする
        '''
        disc_id=self.kwargs['disc_id']
        disc_users = DiscUser.objects.filter(discussion__pk=disc_id)
        return disc_users
    
    def get_context_data(self, **kwargs):
        '''テンプレートに渡すパラメタを改変する
        '''
        context = super().get_context_data(**kwargs)
        
        # 戻るボタン用の disc_id をセット
        context['disc_id'] = self.kwargs['disc_id']
        
        return context


class UsrUpdate(LoginRequiredMixin, UpdateView):
    '''DiscUser の更新ビュー
    '''
    model = DiscUser
    fields = ('is_editor',)
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # 所有権を検査してアクセス中のグループユーザを取得する
        disc_id = self.get_object().discussion.id
        disc_user = test_owner_permission(self, disc_id)
        
        # テンプレートから参照できるよう、ビューの属性にしておく
        self.disc_user = disc_user
        
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        '''保存時のリクエストを受けるハンドラ
        '''
        # 所有権を検査してアクセス中のグループユーザを取得する
        disc_id = self.get_object().discussion.id
        disc_user = test_owner_permission(self, disc_id)
        
        return super().post(request, *args, **kwargs)
    
    def get_success_url(self):
        '''更新に成功した時の遷移先を動的に与える
        '''
        disc_id = self.object.discussion.id
        url = reverse_lazy('discussion:usr_list', kwargs={'disc_id': disc_id})
        return url
    
    def form_valid(self, form):
        '''バリデーションを通った時
        '''
        messages.success(self.request, str(form.instance) + " を更新しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        '''更新に失敗した時
        '''
        messages.warning(self.request, "更新できませんでした。")
        return super().form_invalid(form)


class UsrDelete(LoginRequiredMixin, DeleteView):
    '''DiscUser の削除ビュー
    '''
    model = DiscUser
    template_name_suffix = '_delete'
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # 所有権を検査してアクセス中のグループユーザを取得する
        disc_id = self.get_object().discussion.id
        disc_user = test_owner_permission(self, disc_id)

        # 自分自身を削除することはできない
        if self.get_object() == disc_user:
            raise PermissionDenied
        
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        '''保存時のリクエストを受けるハンドラ
        '''
        # 所有権を検査してアクセス中のグループユーザを取得する
        disc_id = self.get_object().discussion.id
        disc_user = test_owner_permission(self, disc_id)

        # 自分自身を削除することはできない
        if self.get_object() == disc_user:
            raise PermissionDenied
        
        return super().post(request, *args, **kwargs)
    
    def get_success_url(self):
        '''削除に成功した時の遷移先を動的に与える
        '''
        disc_id = self.object.discussion.id
        url = reverse_lazy('discussion:usr_list', kwargs={'disc_id': disc_id})
        return url
    
    def delete(self, request, *args, **kwargs):
        '''削除した時のメッセージ
        '''
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, str(self.object) + " を削除しました。")
        return result


class InvtCreate(LoginRequiredMixin, CreateView):
    '''Invitation の追加ビュー
    '''
    model = Invitation
    fields = ()
    
    def get(self, request, *args, **kwargs):
        '''表示時のリクエストを受けるハンドラ
        '''
        # 所有権を検査してアクセス中のグループユーザを取得する
        disc_user = test_owner_permission(self)
        
        # discussion を view の属性として持っておく
        # テンプレートで固定要素として表示するため
        self.discussion = disc_user.discussion
        
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        '''保存時のリクエストを受けるハンドラ
        '''
        # 所有権を検査してアクセス中のグループユーザを取得する
        disc_user = test_owner_permission(self)
        
        # フォームで入力された「招待する人の ID」
        invitee_value = request.POST['invitee_id']
        
        # それに一致するユーザを view の属性として持っておく
        user_model = get_user_model()
        invitees = user_model.objects.filter(username=invitee_value)
        if len(invitees) > 0:
            self.invitee = invitees[0]
        
        # disc_user, discussion を view の属性として持っておく
        # バリデーションと保存時に使うため
        self.disc_user = disc_user
        self.discussion = disc_user.discussion
        
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        '''バリデーションを通った時
        '''
        # POST ハンドラで招待するユーザを取得できていなかったら、追加失敗
        if not hasattr(self, 'invitee'):
            return self.form_invalid(form)
        
        # グループユーザのユーザ ID リスト
        disc_users = DiscUser.objects.filter(discussion=self.discussion)
        disc_user_user_ids = [disc_user.user.id for disc_user in disc_users]
        
        # 招待中のユーザの ID リスト
        invitations = Invitation.objects.filter(discussion=self.discussion)
        current_invitee_ids = [invt.invitee.id for invt in invitations]
        
        # グループユーザや招待中のユーザを招待することは出来ない。
        if self.invitee.id in disc_user_user_ids\
            or self.invitee.id in current_invitee_ids:
            return self.form_invalid(form)
        
        # 追加しようとするレコードの各フィールドをセット
        instance = form.save(commit=False)
        instance.discussion = self.discussion
        instance.inviter = self.disc_user.user

discussion/templates/discussion/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <title>
        {% if request.path != '/' %}
        {% block title %}{% endblock %} | 
        {% endif %}
        PSCWEB2
    </title>
    
    <!-- for admin widgets -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ form.media }}}
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    <!-- end for admin widgets -->
    
    {% block head %}{% endblock %}
</head>
    
<body>
<div class="container">
    <header>
        {% block header %}
        <a class="site-name">PSCWEB2</a>
        <nav>
            <ul>
                <li>
                    <a href="https://satamame.github.io/pscweb2/demo_help/" target="_blank">?</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                <select name="select" onChange="location.href=value;">
                <option value="#">{{ user.username }}</option>
                <option value="#" class="logout">Logout</option>
                </select>
                </li>
                {% else %}
                <li>
                    <a class="login">Login</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endblock %}
    </header>
    <div class="content">
        {% if messages %}
        <ul class="messagelist">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <!-- div class="breadcrumbs">
            {% block breadcrumbs %}{% endblock %}
        </div -->
        {% block content %}{% endblock %}
    </div>
</div>
{% block javascript %}{% endblock %}
</body>
</html>

discussion/templates/discussion/discuser_delete.html
{% extends 'discussion/base.html' %}

{% block content %}
<h1 style="margin: 0px;">
<a href="{% url 'discussion:usr_list' disc_id=object.discussion.id %}">◀</a>
グループユーザの削除
</h1>

<form method="post">{% csrf_token %}
    <p>このグループユーザを削除しますか？</p>
    <input type="submit" value="削除する">
    <input type="button"
        onclick="location.href='{% url 'discussion:disc_list' %}'"
        value="キャンセル">
</form>

<table>
    <tr><th>グループ</th><td>{{ object.discussion }}</td></tr>
    <tr><th>グループユーザ</th><td>{{ object }}</td></tr>
    <tr><th>所有権</th><td>{{ object.is_owner }}</td></tr>
    <tr><th>編集権</th><td>{{ object.is_editor }}</td></tr>
</table>
{% endblock %}

discussion/templates/discussion/discuser_form.html
{% extends 'discussion/base.html' %}

{% block content %}
<h1 style="margin: 0px;">
<a href="{% url 'discussion:usr_list' disc_id=object.discussion.id %}">◀</a>
グループユーザの編集
</h1>

{% if object != view.disc_user %}
<div align="right"><a href="{% url 'discussion:usr_delete' pk=object.id %}" class="deletelink">削除</a></div>
{% else %}
<div>&nbsp;</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <table>
    <tr><th>グループ</th><td>{{ object.discussion }}</td></tr>
    <tr><th>グループユーザ</th><td>{{ object }}</td></tr>
        {{ form }}
    </table>
    {% if object %}
    <input type="submit" value="更新">
    {% else %}
    <input type="submit" value="作成">
    {% endif %}
</form>
{% endblock %}

discussion/templates/discussion/discuser_list.html
{% extends 'discussion/base.html' %}

{% block content %}

{% if view.disc_user.is_owner and view.invitations %}
<div style="border:solid thin lightgray; border-radius:10px; padding: 10px; margin:5px 0 20px;">
<p><strong>招待中のユーザ</strong></p>
<table>
    <tr>
        <th>ユーザ ID</th>
        <th>姓</th>
        <th>名</th>
        <th>招待の期限</th>
    </tr>
    {% for item in view.invitations %}
    <tr>
        <td>{{ item.invitee.username }}</td>
        <td>{{ item.invitee.last_name }}</td>
        <td>{{ item.invitee.first_name }}</td>
        {% if item.expired %}
            <td style="color:red;">{{ item.exp_dt }}</td>
        {% else %}
            <td>{{ item.exp_dt }}</td>
        {% endif %}
        <td><a href="{% url 'discussion:invt_delete' pk=item.id from='usr_list' %}" class="deletelink">削除</a></td>
    </tr>
{% endfor %}
</table>
</div>
{% endif %}

<h1 style="margin: 0;">
<a>◀</a>
メンバ一覧
</h1>
{% if view.disc_user.is_owner %}
<div align="right"><a href="{% url 'discussion:invt_create' disc_id=disc_id %}" class="addlink">招待する</a></div>
{% else %}
<div>&nbsp;</div>
{% endif %}

<table>
    <tr>
        <th>ユーザ名</th>
        <th>ID</th>
        <th>所有権</th>
        <th>編集権</th>
    </tr>
    {% for item in object_list %}
    <tr>
        <td>{{ item }}</td>
        <td>{{ item.user.username }}</td>
        <td>{{ item.is_owner }}</td>
        <td>{{ item.is_editor }}</td>
        {% if view.disc_user.is_owner %}
        <td>
            <a href="{% url 'discussion:usr_update' pk=item.id %}" class="changelink">編集</a>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

discussion/templates/discussion/discussion_delete.html
{% extends 'discussion/base.html' %}

{% block content %}
<h1 style="margin: 0px;">
<a href="{% url 'discussion:disc_list' %}">◀</a>
グループの削除
</h1>

<form method="post">{% csrf_token %}
    <p>このグループを削除しますか？</p>
    <input type="submit" value="削除する">
    <input type="button"
        onclick="location.href='{% url 'discussion:disc_list' %}'"
        value="キャンセル">
</form>

<table>
    <tr><th>グループ</th><td>{{ object.name }}</td></tr>
</table>
{% endblock %}

discussion/templates/discussion/discussion_form.html
{% extends 'discussion/base.html' %}

{% block content %}
<h1 style="margin: 0px;">
<a href="{% url 'discussion:disc_list' %}">◀</a>
{% if object %}
グループの編集
{% else %}
新規グループ
{% endif %}
</h1>

{% if object %}
<div align="right"><a href="{% url 'discussion:disc_delete' pk=object.id %}" class="deletelink">削除</a></div>
{% else %}
<div>&nbsp;</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    {% if object %}
    <input type="submit" value="更新">
    {% else %}
    <input type="submit" value="作成">
    {% endif %}
</form>
{% endblock %}

discussion/templates/discussion/discussion_join.html
{% extends 'discussion/base.html' %}

{% block content %}
<h1 style="margin: 0px;">
<a href="{% url 'discussion:disc_list' %}">◀</a>
グループに参加
</h1>

<div>&nbsp;</div>

<p>
{{ view.discussion }} に招待されています。参加しますか？
</p>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="discussion" value="{{ view.discussion.id }}">
    <input type="hidden" name="user" value="{{ view.request.user.id }}">
    <input type="submit" value="参加">
    <input type="button"
        onclick="location.href='{% url 'discussion:disc_list' %}'"
        value="あとで">
</form>
{% endblock %}

discussion/templates/discussion/discussion_list.html
{% extends 'discussion/base.html' %}

{% block content %}

{% if view.invitations %}
<div style="border:solid thin lightgray; border-radius:10px; padding: 10px; margin:5px 0 20px;">
<p><strong>招待されているグループ</strong></p>
<table>
    <tr>
        <th>グループ名</th>
        <th>招待主の ID</th>
        <th>招待の期限</th>
    </tr>
    {% for item in view.invitations %}
    <tr>
        <td>{{ item.discussion }}</td>
        <td>{{ item.inviter.username }}</td>
        {% if item.expired %}
            <td style="color:red;">{{ item.exp_dt }}</td>
        {% else %}
            <td>{{ item.exp_dt }}</td>
        {% endif %}
        <td>
            <a href="{% url 'discussion:disc_join' invt_id=item.id %}" class="addlink">参加</a>
            <a href="{% url 'discussion:invt_delete' pk=item.id from='disc_list' %}" class="deletelink">削除</a>
        </td>
    </tr>
{% endfor %}
</table>
</div>
{% endif %}

<h3 style="margin: 0px;">参加グループ一覧</h3>
<div align="right"><a href="{% url 'discussion:disc_create' %}" class="addlink">新規作成</a></div>

<nav aria-label="breadcrumb">
    {% for item in object_list %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'nblog1:top' %}">{{ item.discussion }}</a></li>
        {% if item.is_owner %}
        <li class="breadcrumb-item"><a href="{% url 'discussion:invt_create' disc_id=item.discussion.id %}">招待</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'discussion:disc_update' pk=item.discussion.id %}">編集</a></li>
        {% endif %}
    </ol>
    {% endfor %}
</nav>

{% endblock %}